Unified tests
funkwerk/DMocks-revived pull request #6
Opened 2017-10-04 08:55 UTC by belka-ew

This is the first step to restructure dmocks.

The unittests are currently hidden in a set of version blocks like:
- DMocksTest
- DMocksDebug
- DMocksTestStandalone

So if you run `dub test` without `--config DMocksTest`, the tests are just skipped.
This PR removes these unittest version blocks, so the tests aren't skipped. It also comments out several tests that were already broken in the original DMocks-revived repository and probably should be reviewed later.

2017-10-04 11:51 UTC, linkrope requested changes
- can you remove the obsolete `test` template?
- can you name `unittest` functions `@("like this")`
  (works with unit-threaded, but does not require unit-threaded)
- why `private unittest`?

2017-10-04 14:13 UTC, belka-ew commented
1). `test` was removed before its usage: [fbab160](https://github.com/funkwerk/DMocks-revived/commit/fbab16036f4e42be69f1d13f39d6c24a61922ed5)
3). [Documented Unittests](https://dlang.org/spec/unittest.html#documented-unittests):

> A unittest which is not documented, or is marked as private will not be used to generate code samples.

2017-10-05 15:41 UTC, linkrope commented on dmocks/mocks.d
> +    } catch (Exception e) {}
`assert(false, ...);` is missing?
Consider using `assertThrown` instead.

2017-10-06 15:01 UTC, linkrope requested changes
ugly indentation for optional `msg` of `assertThrown`
(default message "assertThrown failed: No ... was thrown." is good enough)

2017-10-06 15:05 UTC, belka-ew commented
@linkrope, do you mean just remove "Expected exception not thrown"?

2017-10-07 14:45 UTC, linkrope approved these changes

2017-10-07 14:54 UTC, merged